language: python
env:
  - TOOLS="check50 compare50"
python: 3.6
addons:
  apt:
    update: true
    packges:
     - tree
install:
  - pip install --upgrade --requirement requirements.txt
  - for tool in $TOOLS; do rm --force --recursive /tmp/$tool && git clone --branch develop --depth 1 https://github.com/cs50/$tool.git /tmp/$tool; done
  - for tool in $TOOLS; do pip install /tmp/$tool && mv /tmp/$tool/docs/source $tool && rm --force --recursive /tmp/$tool; done
script:
  - make html && rm --force --recursive _build
  - tree _build
  - cat _build/html/compare50/dev.html
deploy:
  provider: script
  script: 'git remote set-url origin "https://$USERNAME:$PASSWORD@github.com/cs50/manual50.git" && git branch --delete rel || true && git checkout -b rel && git add --all --force && git commit --allow-empty --message "$(date) [skip ci]" && git push --force origin rel'
  skip_cleanup: true
